### ISSUE TITLE
Consulta sobre las entidades

### ISSUE THREAD

**Issue by manuelj555** [csalazart/RegionesBundle#6]
Revisando las entidades veo que por ejemplo la entidad **Municipio** posee un atributo **idciudad**:
https://github.com/csalazart/RegionesBundle/blob/master/Entity/Municipio.php#L36
El cual no es una Relacion ManyToOne, sino un integer y no se si se deba hacer el cambio allí.

Por otro lado la entidad **Parroquia** tiene dos atributos, **municipio** y **estado**, alli pienso que el atributo estado queda sobrando, ya que el municipio de por sí sen encuentra (relacionado) dentro de un estado.

Me parece importante definir esto, para poder crear los subscriber de formularios para manejar estas dependencias.

**Comment by csalazart** [comment]
Si es correcto es un trabajo en proceso y ha quedado un poco relegado pero voy editando.. GRacias!!
